### ISSUE TITLE
Some ideas to improve functionality

### ISSUE THREAD

**Issue by paszti19** [moddavid/Ancud_ShortURL-portlet#1]
Dear Developer,

First of all, i'd like to thank you for this plugin, it is really useful. We are managing short urls in our current system with the built-in site pages, which are redirecting to Liferay layouts or custom urls. This method is a bit ugly, and hard to manage. 
We could replace our current method with your portlet, but i would have some feature requests that improves functionality/usability:

1) configure the portlet to be in ControlPanel ("site" section), because these short urls are global site configurations
2) support for putting shorturls in folders
3) ability to set a name and/or description for the shorturl
4) support Liferay layout selection when defining redirect page
5) support Liferay document&media selection when defining redirect page
6) listen for shorturls on a custom servlet context (ex: /s/*), to not to get in conflict with standard site layout urls

Thanks!

**Comment by moddavid** [comment]
Hi paszti19,

these requests are possible to realize. As this is open source, you have many possibilities:
1. fork the project and do everything by yourself
2. wait for me to do it, which is a bad option, as I currently cannot spend too much time on this
3. pay a developer to do it - in this case the source would be merged here again, which will help everyone

If you want to choose 3, you can go to the Portlet Page in the Liferay Marketplace and use the support contact informations.
